### ISSUE TITLE
Stabilization & Maturity

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/roadmap#3]
As we see more and more people using our tools we will focus on fixing stability and maturity issues and will focus on HDFS and HBase in this release.

```[tasklist]
- [ ] https://github.com/stackabletech/docker-images/issues/332
- [ ] https://github.com/stackabletech/issues/issues/359
- [ ] https://github.com/stackabletech/hbase-operator/issues/405
- [ ] https://github.com/stackabletech/docker-images/issues/359
```

**Comment by sbernauer** [comment]
@lfrancke I would like to add https://github.com/stackabletech/hbase-operator/issues/260 to this Issue, WDYT?
